server.port=8080

spring.application.name=flowable

# Database
spring.datasource.url=jdbc:h2:mem:flowable;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Flowable
flowable.database-schema-update=true
flowable.async-executor-activate=true

# Logging
logging.level.org.flowable=INFO
logging.level.org.springframework=INFO
